@startuml
title __Zweite Normalform (2ONF)__
skinparam classAttributeIconSize 0
class Abo{
-Beginn: long
-Gebuehr: long
-Art: int
}
class Kunde{
-Adresse: String
-Firma: boolean
+buyAbo(): void
+parkeAuto(): void

}
class ParkAuto {
-parkBeginn: long
-parkEnde: long
-parkDauer: int
-parkGebuehr: int
-bezahlArt: int
+bezahlen(): boolean
}
class Auto{
-KfzKennzeichen: String
}
class Parkplatz{
-Nummer: int
}
ParkAuto -down-> Parkplatz
Kunde -- ParkAuto
Kunde -right-> Abo
Kunde -left-> Auto
Abo -down-> Parkplatz

@enduml